In [6]:
import numpy as np

a= [1,3,5,"a","b"] # 1,3,5 숫자 , 'a','b' 문자
print(a)
b = np.array([1,3,5,"a","b"]) # '1','3','5','a','b' 문자로 통일
print(b)

[1, 3, 5, 'a', 'b']
['1' '3' '5' 'a' 'b']


In [7]:
# 리스트안에 리스트 크기가 고정되지 않아도 문제 x
a = [[1],[3,5],[2,4,6]]

# b = np.array([[1],[3,5],[2,4,6]])
c = np.array([[1,2],[3,5],[2,6]])
print(a)
print(c)

[[1], [3, 5], [2, 4, 6]]
[[1 2]
 [3 5]
 [2 6]]


In [8]:
# 리스트 연산

a = [1,3,5]
b = [2,4,6]
c = [0,0]

# 1, 3, 5, 2, 4, 6
print(a+b)

# 1, 3, 5, 2, 4, 6, 0, 0
print(a+b+c)

# 1, 3, 5, 1, 3, 5, 1, 3, 5
print(a*3)

[1, 3, 5, 2, 4, 6]
[1, 3, 5, 2, 4, 6, 0, 0]
[1, 3, 5, 1, 3, 5, 1, 3, 5]


In [9]:
# numpy 배열 연산

a = np.array([1,3,5])
b = np.array([2,4,6])

# 각 인데스를 더해준 배열
# 1+2, 3+4, 5+6
print(c)

# 1*2, 3*4, 5*6
print(a*b)
# 1+2, 3+2 ,5+2
print(a+2)

# 1*3, 3*3, 5*3
print(a*3)

[0, 0]
[ 2 12 30]
[3 5 7]
[ 3  9 15]


In [18]:
# numpy 배열 메소드

a= [1,3,5]
b = np.array([1,3,5])

# a.mean()
print(b.mean())
print(b.argmax())
print(b.round())

c = np.array([[[1,2,3,1],[4,5,6,1]],[[11,2,3,1],[14,15,16,11]]])
print(c.shape)
print("c 슬라이싱")
print(c[0,0,:])
print(c[1,:1,:])
print(c[:,:,2])
d = np.array([[0,1,2,3],[4,5,6,7]])
print(d[0,:])
print(d[1,:])
print(d[:,0])

3.0
2
[1 3 5]
(2, 2, 4)
c 슬라이싱
[1 2 3 1]
[[11  2  3  1]]
[[ 3  6]
 [ 3 16]]
[0 1 2 3]
[4 5 6 7]
[0 4]


In [30]:
test =np.array([[[[1,2,3,4,5],[6,7,8,9,10]],
                 [[11,12,13,14,14],[16,17,18,19,20]]],
                 [[[21,22,23,24,25],[26,27,28,29,30]],
                 [[31,32,33,34,35],[36,37,38,39,40]]]])
print(test.shape)
print(test[:,:,:,4])
print(test[0,::3])

(2, 2, 2, 5)
[[[ 5 10]
  [14 20]]

 [[25 30]
  [35 40]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
